version: '3.1'
services:
  stats-server:
    build: ./stats
    container_name: stats-service
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      DB_HOST: stats-db
      DB_PORT: 5432
      DB_NAME: stats
      DB_USER: stats
      DB_PASS: stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./stats_db:/var/lib/postgresql/data

  ewm-service:
    build: ./main
    container_name: ewm-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      DB_HOST: ewm-db
      DB_PORT: 5432
      DB_NAME: main
      DB_USER: main
      DB_PASS: main
      STATS_SERVER_URL: http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./ewm_db:/var/lib/postgresql/data
